[extra]
author = "Jacob"

[format.markdown]
link-format = "[[{{rel-path}}|{{title}}]]"
link-encode-path = false
link-drop-extension = true
hashtags = true
colon-tags = false
multiword-tags = true

[tool]
pager = ""

[alias]
home = 'zk edit $ZK_NOTEBOOK_DIR/index.md'
